services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile.backer
    container_name: almostaykhan-app
    ports:
      - "8000:8000"
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    volumes:
      - ./backer/data:/app/backer/data
      - ./scraper/output:/app/scraper/output
